//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassini.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentActStatus
    {
        public int id { get; set; }
        public System.Guid gid { get; set; }
        public string Name { get; set; }
        public bool IsRemovable { get; set; }
        public bool IsEditable { get; set; }
        public bool IsStornable { get; set; }
    }
}
