//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassini.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentChanel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentChanel()
        {
            this.AgentChanels1 = new HashSet<AgentChanel>();
        }
    
        public long id { get; set; }
        public System.Guid gid { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ParentGID { get; set; }
        public bool IsPremium { get; set; }
        public Nullable<System.Guid> DocumentTypeGID { get; set; }
        public Nullable<System.Guid> ChanelPaymentTypeGID { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentChanel> AgentChanels1 { get; set; }
        public virtual AgentChanel AgentChanel1 { get; set; }
    }
}
