//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassini.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Branches1 = new HashSet<Branch>();
        }
    
        public long id { get; set; }
        public System.Guid gid { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ParentGID { get; set; }
        public Nullable<System.Guid> OrganizationGID { get; set; }
        public Nullable<System.Guid> DirectorGID { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> ControlBlanks { get; set; }
        public Nullable<System.Guid> BranchCategoryGID { get; set; }
        public Nullable<System.Guid> AuthorGID { get; set; }
        public Nullable<int> Level { get; set; }
        public bool IsBlanksAvailable { get; set; }
        public bool IsClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branches1 { get; set; }
        public virtual Branch Branch1 { get; set; }
    }
}
