//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassini.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CallistoDb : DbContext
    {
        public CallistoDb()
            : base("name=CallistoDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<AgentActStatus> AgentActStatuses { get; set; }
        public virtual DbSet<AgentChanel> AgentChanels { get; set; }
        public virtual DbSet<CommissionType> CommissionTypes { get; set; }
    
        [DbFunction("CallistoDb", "AgentActsComissionsSum")]
        public virtual IQueryable<AgentActsComissionsSum_Result> AgentActsComissionsSum(Nullable<System.DateTime> period, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<System.Guid> statusGID, Nullable<System.Guid> commissionType)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(System.DateTime));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var statusGIDParameter = statusGID.HasValue ?
                new ObjectParameter("StatusGID", statusGID) :
                new ObjectParameter("StatusGID", typeof(System.Guid));
    
            var commissionTypeParameter = commissionType.HasValue ?
                new ObjectParameter("CommissionType", commissionType) :
                new ObjectParameter("CommissionType", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<AgentActsComissionsSum_Result>("[CallistoDb].[AgentActsComissionsSum](@Period, @StartDate, @EndDate, @StatusGID, @CommissionType)", periodParameter, startDateParameter, endDateParameter, statusGIDParameter, commissionTypeParameter);
        }
    
        [DbFunction("CallistoDb", "GetDirections")]
        public virtual IQueryable<GetDirections_Result> GetDirections()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDirections_Result>("[CallistoDb].[GetDirections]()");
        }
    }
}
