//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassini.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionType
    {
        public long id { get; set; }
        public System.Guid gid { get; set; }
        public string Caption { get; set; }
        public string Code { get; set; }
        public bool IsNullable { get; set; }
        public bool IsRequired { get; set; }
        public bool IsContragent { get; set; }
        public Nullable<System.Guid> ParentGID { get; set; }
        public bool IsCascade { get; set; }
    }
}
